profile:
  cv_file: Aakash_khadka_CV.pdf
  cv_skills_extracted:
  - S3
  - aws
  - bash
  - ci/cd
  - cloudwatch
  - data engineering
  - data science
  - deep learning
  - docker
  - ec2
  - elasticsearch
  - elt
  - etl
  - git
  - hadoop
  - java
  - lambda
  - langchain
  - linux
  - llm
  - machine learning
  - maven
  - nlp
  - numpy
  - pandas
  - postgresql
  - protobuf
  - pyspark
  - python
  - pytorch
  - rag
  - react
  - scikit-learn
  - spark
  - sql
  updated_at: '2026-04-19T15:07:33.530974Z'
