profile:
  cv_file: uploaded_cv.pdf
  cv_skills_extracted:
  - S3
  - aws
  - data science
  - deep learning
  - django
  - docker
  - ec2
  - elasticsearch
  - git
  - hadoop
  - java
  - linux
  - llm
  - machine learning
  - maven
  - numpy
  - pandas
  - pyspark
  - python
  - pytorch
  - rag
  - react
  - scikit-learn
  - spark
  - sql
  updated_at: '2026-05-05T05:45:12.351050Z'
